server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  #incicates the duration the server waits since it received
  #the last heartbeat before it can evict an instance from its registry
  instance:
    lease-expiration-duration-in-seconds: 20


